version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./src/server/.env
    depends_on:
      - db

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
